# Generated by Django 4.0 on 2021-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('streetNumber', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
