# Generated by Django 4.0 on 2021-12-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.seasons'),
        ),
    ]
