# Generated by Django 4.0 on 2021-12-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_tire_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
